### ISSUE TITLE
🐛  RN - 0.74.1, Kotlin - 1.9.22 - Execution failed for task ':react-native-vision-camera:compileDebugKotlin'

### ISSUE THREAD

**Issue by enchorb** [cuvent/react-native-vision-camera#2870]
### What's happening?

Getting `Execution failed for task ':react-native-vision-camera:compileDebugKotlin'` on React Native `0.74.1` which updated Kotlin to `1.9.22`.

Was previously working on React Native `0.73.8` & Kotlin `1.8.0`

### Reproduceable Code

```tsx
N/A
```

### Relevant log output

```shell
Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error.
```

### Camera Device

```json
N/A
```

### Device

Android

### VisionCamera Version

4.0.3

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by enchorb** [comment]
closing, duplicate of: https://github.com/mrousavy/react-native-vision-camera/issues/2851
